"""empty message

Revision ID: cf0d67aaf5f5
Revises: 
Create Date: 2025-11-09 18:27:42.418287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf0d67aaf5f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SUBMITTED', 'ACKNOWLEDGED', 'RESOLVED', name='incident_status_enum').create(op.get_bind())
    sa.Enum('OPERATOR', 'MONITORING', 'PARTNER', name='incident_source_enum').create(op.get_bind())
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', postgresql.ENUM('OPERATOR', 'MONITORING', 'PARTNER', name='incident_source_enum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_updated_at'), 'incidents', ['updated_at'], unique=False)
    op.create_table('incident_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('value', postgresql.ENUM('SUBMITTED', 'ACKNOWLEDGED', 'RESOLVED', name='incident_status_enum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_statuses_incident_id_incidents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_statuses'))
    )
    op.create_index(op.f('ix_incident_statuses_created_at'), 'incident_statuses', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_statuses_updated_at'), 'incident_statuses', ['updated_at'], unique=False)
    op.create_index(op.f('ix_incident_statuses_value'), 'incident_statuses', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_statuses_value'), table_name='incident_statuses')
    op.drop_index(op.f('ix_incident_statuses_updated_at'), table_name='incident_statuses')
    op.drop_index(op.f('ix_incident_statuses_created_at'), table_name='incident_statuses')
    op.drop_table('incident_statuses')
    op.drop_index(op.f('ix_incidents_updated_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_table('incidents')
    sa.Enum('OPERATOR', 'MONITORING', 'PARTNER', name='incident_source_enum').drop(op.get_bind())
    sa.Enum('SUBMITTED', 'ACKNOWLEDGED', 'RESOLVED', name='incident_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
