"""empty message

Revision ID: f63cc3fd660a
Revises: cf0d67aaf5f5
Create Date: 2025-11-09 18:27:50.400610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63cc3fd660a'
down_revision: Union[str, Sequence[str], None] = 'cf0d67aaf5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_incidents_status_id'), 'incidents', ['status_id'])
    op.create_foreign_key(op.f('fk_incidents_status_id_incident_statuses'), 'incidents', 'incident_statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_incidents_status_id_incident_statuses'), 'incidents', type_='foreignkey')
    op.drop_constraint(op.f('uq_incidents_status_id'), 'incidents', type_='unique')
    op.drop_column('incidents', 'status_id')
    # ### end Alembic commands ###
